### ISSUE TITLE
Extension fields missing from GIMBAL_DEVICE_ATTITUDE_STATUS_DATA

### ISSUE THREAD

**Issue by av-stefan** [mavlink/rust-mavlink#282]
On both 0.12.1 and 0.13.1, I do not get access to the fields gimbal_device_id or camera_device_id which are extension fields, even when using the emit-extensions feature.

**Comment by pv42** [comment]
There was a bug in 0.13.x that the feature was not properly set on the `mavlink-bindgen` crate when using the mavlink crate. This was fixed with #248 and it should work now on master. You will have to use a git dependency for now until it gets released to crates.io.

Unsure why it doesn't work for 0.12.

**Comment by pv42** [comment]
Nevermind.
This currently depends on an older version of the MAVLink message definitions that do not have that extension field yet. Therefore it does not get generated. 
https://github.com/mavlink/mavlink/blob/d6d86d3f0c90a67c275d6833931f7c712b858dba/message_definitions/v1.0/common.xml#L7013

**Comment by av-stefan** [comment]
Alright, closing since already fixed then
